routes:
  /signup/: members\signup
  /signin/: members\signin
  /account/: members\account

collections:
  /:
    permalink: /{slug}/
    template: index
  /blog/:
    permalink: /{slug}/
    template: tag
    filter: tag:blog

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
